spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/re-data-jpa
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
        ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #show_sql: true

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace #스프링 부트 3.x, hibernate6


